feat: multi instance support
instill-ai/cli pull request #178
Opened 2023-09-15 13:06 UTC by TobiaszCudnik

Because

- (write the reason why we need to consider this PR in a list)

This commit

- (write the summary of all commits in this PR in a list)

2023-09-21 22:19 UTC, pinglin requested changes
Please see the comments and suggested changes.

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/edit_test.go
> +)
```suggestion
import (
	"bytes"
	"testing"

	"github.com/google/shlex"
	"github.com/stretchr/testify/assert"

	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/pkg/cmdutil"
	"github.com/instill-ai/cli/pkg/iostreams"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/instances.go
> +)
```suggestion
import (
	"github.com/spf13/cobra"

	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/pkg/cmdutil"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/list.go
> +)
```suggestion
import (
	"fmt"
	
	"github.com/spf13/cobra"
	
	"github.com/MakeNowJust/heredoc"
	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/pkg/cmdutil"
	"github.com/instill-ai/cli/pkg/iostreams"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/list_test.go
> +)
```suggestion
import (
	"bytes"
	"testing"

	"github.com/google/shlex"
	"github.com/stretchr/testify/assert"

	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/pkg/cmdutil"
	"github.com/instill-ai/cli/pkg/iostreams"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/remove.go
> +)
```suggestion
import (
	"fmt"
	
	"github.com/MakeNowJust/heredoc"
	"github.com/spf13/cobra"

	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/internal/instance"
	"github.com/instill-ai/cli/pkg/cmdutil"
	"github.com/instill-ai/cli/pkg/iostreams"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/remove_test.go
> +)
```suggestion
import (
	"bytes"
	"testing"

	"github.com/google/shlex"
	"github.com/stretchr/testify/assert"

	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/pkg/cmdutil"
	"github.com/instill-ai/cli/pkg/iostreams"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/set_default.go
> +)
```suggestion
import (
	"fmt"

	"github.com/MakeNowJust/heredoc"
	"github.com/spf13/cobra"

	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/internal/instance"
	"github.com/instill-ai/cli/pkg/cmdutil"
	"github.com/instill-ai/cli/pkg/iostreams"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/set_default_test.go
> +)
```suggestion
import (
	"bytes"
	"testing"

	"github.com/google/shlex"
	"github.com/stretchr/testify/assert"

	"github.com/instill-ai/cli/internal/config"
	"github.com/instill-ai/cli/pkg/cmdutil"
	"github.com/instill-ai/cli/pkg/iostreams"
)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmdutil/auth_check_test.go
> +	"path/filepath"
please re-arrange import packages

2023-09-21 22:19 UTC, pinglin commented on internal/oauth2/auth_code_flow.go
> +	auth, err := NewAuthenticator(issuer, host.Oauth2ClientID, host.Oauth2Secret, callbackHost, port)
```suggestion
	auth, err := NewAuthenticator(issuer, host.Oauth2ClientID, host.Oauth2ClientSecret, callbackHost, port)
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/add.go
> +	host.Oauth2Secret = opts.Secret
```suggestion
	host.Oauth2ClientSecret = opts.ClientSecret
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/add.go
> +	if opts.Oauth2 != "" && (opts.Secret == "" || opts.ClientID == "") {
```suggestion
	if opts.Oauth2 != "" && (opts.ClientSecret == "" || opts.ClientID == "") {
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/edit.go
> +		host.Oauth2Secret = ""
```suggestion
		host.Oauth2ClientSecret = ""
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/edit.go
> +		if (host.Oauth2Secret == "" || host.Oauth2ClientID == "") && (opts.Secret == "" || opts.ClientID == "") {
```suggestion
		if (host.Oauth2ClientSecret == "" || host.Oauth2ClientID == "") && (opts.ClientSecret == "" || opts.ClientID == "") {
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/edit.go
> +			host.Oauth2Secret = opts.Secret
```suggestion
			host.Oauth2ClientSecret = opts.ClientSecret
```

2023-09-21 22:19 UTC, pinglin commented on internal/config/from_file.go
> +	Oauth2Secret   string
```suggestion
	Oauth2ClientSecret   string
```

2023-09-21 22:19 UTC, pinglin commented on internal/config/from_file.go
> +	ht.Oauth2Secret = conf.GetOptionalStringValue("oauth2_secret")
```suggestion
	ht.Oauth2ClientSecret = conf.GetOptionalStringValue("oauth2_client_secret")
```

2023-09-21 22:19 UTC, pinglin commented on internal/config/from_file.go
> +	err = conf.SetStringValue("oauth2_secret", host.Oauth2Secret)
```suggestion
	err = conf.SetStringValue("oauth2_client_secret", host.Oauth2ClientSecret)
```

2023-09-21 22:19 UTC, pinglin commented on internal/config/from_file_test.go
> +	assert.Equal(t, "bar2", hct.Oauth2Secret)
```suggestion
	assert.Equal(t, "bar2", hct.Oauth2ClientSecret)
```

2023-09-21 22:19 UTC, pinglin commented on internal/config/from_file_test.go
> +	_ = hc.SetStringValue("oauth2_secret", "bar2")
```suggestion
	_ = hc.SetStringValue("oauth2_client_secret", "bar2")
```

2023-09-21 22:19 UTC, pinglin commented on internal/config/stub.go
> +	_ = c.Set(h, "oauth2_secret", host.Oauth2Secret)
```suggestion
	_ = c.Set(h, "oauth2_client_secret", host.Oauth2ClientSecret)
```

2023-09-21 22:19 UTC, pinglin commented on internal/oauth2/auth_code_flow.go
> +	host.Oauth2Secret = clientSecret
```suggestion
	host.Oauth2ClientSecret = clientSecret
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/auth/login/login.go
> +	if host.Oauth2Hostname == "" || host.Oauth2ClientID == "" || host.Oauth2Secret == "" {
```suggestion
	if host.Oauth2Hostname == "" || host.Oauth2ClientID == "" || host.Oauth2ClientSecret == "" {
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/add_test.go
> +				v, err = cfg.Get("foo", "oauth2_secret")
```suggestion
				v, err = cfg.Get("foo", "oauth2_client_secret")
```

2023-09-21 22:19 UTC, pinglin commented on pkg/cmd/instances/edit_test.go
> +				v, err = cfg.Get("api.instill.tech", "oauth2_secret")
```suggestion
				v, err = cfg.Get("api.instill.tech", "oauth2_client_secret")
```

2023-09-22 08:09 UTC, TobiaszCudnik commented
> Please see the comments and suggested changes.

@pinglin Ive implemented the renames and formatted imports. Im happy theres no concerns regarding the code itself. We should incorporate `goimports` into the pipeline.

2023-09-22 08:21 UTC, pinglin commented on internal/config/stub.go
> +			Oauth2ClientID: "barfoo",
Given the specialty of this file, we will need to set a skip rule for it in the CodeQL GA workflow to avoid false alarm.

2023-09-22 08:23 UTC, pinglin commented
> > Please see the comments and suggested changes.
> 
> @pinglin Ive implemented the renames and formatted imports. Im happy theres no concerns regarding the code itself. We should incorporate `goimports` into the pipeline.

Yeah, that will be very ideal. @praharshjain has proposed and tried it before actually. Any guideline for this?

2023-09-22 08:52 UTC, pinglin commented on pkg/cmd/auth/logout/logout.go
> +		Short: "Log out of an Instill instance",
Good point. We make this more explicit then.

```suggestion
		Short: "Log out of an Instill Core or Instill Cloud instance",
```

2023-09-22 08:53 UTC, TobiaszCudnik commented
This seems to be the right source:
https://github.com/dnephin/pre-commit-golang

Import order should be linted, like any other required conventions. AFAIK we're using the default golangci-lint config.

2023-09-22 08:54 UTC, pinglin commented on pkg/cmd/auth/login/login.go
> +				--secret SECRET`, hostname, hostname)
Prefer explicitly here.

2023-09-22 09:07 UTC, TobiaszCudnik commented on internal/config/stub.go
> +			Oauth2ClientID: "barfoo",
There is no suppression by annotation, only in the UI. It wont pop up unless the line is modified. This is the official way of handling it.

2023-09-22 16:55 UTC, pinglin approved these changes
LGTM

2023-09-22 17:09 UTC, merged